### ISSUE TITLE
포켓몬 도감 상태 / feature_pokemon_list

### ISSUE THREAD

**Issue by alphaorderly** [nexusbusim/PokemonGuide#5]
추가할 기능
- 포켓몬 도감 상태
    - 포획여부
    - 만남여부
- 포켓몬 리스트는 앱에 하드코딩으로 저장.

**Comment by alphaorderly** [comment]
완성된 기능
- 포켓몬 도감 나열
- 검색
- 포켓몬 본 여부
- 포켓몬 잡은 여부

필요한 기능
- 현재 상태 asyncstorage에 저장하기 = 완료
- 검색창 옆에 설정버튼 = 완료
    - 잡지 않은 포켓몬만 보기 = 완료
    - 보지 않은 포켓몬만 보기 = 완료
- 링크를 사파리가 아닌 내장 웹뷰로 열도록 하기 = 완료

테스트
- 다른 앱 화면에서도 잘 보이는지 테스트 할것 = 완료

**Comment by alphaorderly** [comment]
추가
- 도감 초기화 버튼 = 완료
- 리스트 왼쪽에 자그마한 그림 = 완료

**Comment by nexusbusim** [comment]
개발완료
